accounts/urls.py
from django.urls import path
from .views import UserSignupView, UserSignInView, UserLogoutView, UserProfileView, change_password

urlpatterns = [
    path("signup/", UserSignupView.as_view(), name="signup"),
    path("signin/", UserSignInView.as_view(), name="signin"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path("change-password/", change_password, name="change_pass"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

bank_management/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("transactions/", include("transactions.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bank_software/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path("accounts/", include("accounts.urls"))
]

transactions/urls.py
from django.urls import path
from .views import DepositMoneyView, WithdrawView, LoanRequestView, TransactionReportView, LoanListView, PayLoanView, MoneyTransferView


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit"),
    path("withdraw/", WithdrawView.as_view(), name="withdraw"),
    path("loan-request/", LoanRequestView.as_view(), name="loan_request"),
    path("money-transfer/", MoneyTransferView.as_view(), name="money_transfer"),
    path("loans/", LoanListView.as_view(), name="loan_list"),
    path("report/", TransactionReportView.as_view(),
         name="transaction_report"),
    path("loans/<int:loan_id>/", PayLoanView.as_view(), name="pay"),
]

transactions/models.py
from django.db import models
from accounts.models import UserBankAccountModel
# Create your models here.
from .constants import TRANSACTION_TYPE


class TransactionModel(models.Model):
    account = models.ForeignKey(
        UserBankAccountModel, related_name='transactions', on_delete=models.CASCADE)

    amount = models.DecimalField(decimal_places=2, max_digits=12)
    balance_after_transaction = models.DecimalField(
        decimal_places=2, max_digits=12)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approve = models.BooleanField(default=False)

    class Meta:
        ordering = ['timestamp']

transactions/forms.py
from django import forms
from .models import TransactionModel


class TransactionForm(forms.ModelForm):
    class Meta:
        model = TransactionModel
        fields = ["amount", "transaction_type"]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class DepositForm(TransactionForm):
    def clean_amount(self):
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount')
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )

        return amount


class WithdrawForm(TransactionForm):
    def clean_amount(self):
        account = self.account
        min_withdraw_amount = 500
        max_withdraw_amount = 20000
        balance = account.balance  # 1000
        amount = self.cleaned_data.get('amount')
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )

        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )

        if amount > balance:
            raise forms.ValidationError(
                f'You have {balance} $ in your account. '
                'You can not withdraw more than your account balance'
            )

        return amount


class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')

        return amount


class MoneyTransferForm(forms.Form):
    account_no = forms.IntegerField()
    amount = forms.DecimalField(max_digits=12, decimal_places=2)

transactions/views.py
from typing import Any
from django.shortcuts import get_object_or_404, redirect, render
from .models import TransactionModel
from django.views.generic import CreateView, ListView
from django.views import View
from .constants import DEPOSIT, WITHDRAWAL, LOAN, LOAN_PAID, RECEIVED, TRANSFERRED
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import DepositForm, WithdrawForm, LoanRequestForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from .utils.sendEmail import send_transaction_emails
from .forms import MoneyTransferForm
from accounts.models import UserBankAccountModel
from transactions.models import TransactionModel
# Create your views here.


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = "transactions/transaction_form.html"
    model = TransactionModel
    success_url = reverse_lazy("transaction_report")
    title = ""

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            "account": self.request.user.account
        })
        return kwargs

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context.update({
            "title": self.title
        })
        return context


class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit'

    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount
        account.save(
            update_fields=[
                'balance'
            ]
        )

        messages.success(self.request, f"""{"{:,.2f}".format(
            float(amount))}$ was deposited to your account successfully""")

        send_transaction_emails(
            self.request.user,
            self.request.user.email,
            f"Balance Deposited A/C {account.account_no}",
            f"""Your deposit request for ${amount} has successfully completed. After depsoit your total amount is{account.balance}""")

        return super().form_valid(form)


class WithdrawView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = "Withdraw"

    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account

        if account.isBankrupt:
            messages.error(
                self.request, f"""Sorry your account has been Bankrupt""")
            return redirect("profile")

        account.balance -= amount
        account.save(
            update_fields=[
                'balance'
            ]
        )

        messages.success(self.request, f"""
        {"{:,.2f}".format(float(amount))}$ was withdrawn to your account successfully""")

        send_transaction_emails(
            self.request.user,
            self.request.user.email,
            f"Balance Withdrawal A/C {account.account_no}",
            f"""Your withdrawal request for ${amount} has successfully completed. After withdraw your total amount is ${account.balance}""")

        return super().form_valid(form)


class LoanRequestView(TransactionCreateMixin):
    form_class = LoanRequestForm
    title = "Request For Loan"

    def get_initial(self):
        initial = {'transaction_type': LOAN}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        loan_count = TransactionModel.objects.filter(
            account=account, transaction_type=LOAN, loan_approve=True).count()

        if loan_count >= 3:
            return HttpResponse("You have cross the loan limits")

        messages.success(
            self.request,
            f"""Loan request for {"{:,.2f}".format(float(amount))}$ submitted successfully""")

        send_transaction_emails(
            self.request.user,
            self.request.user.email,
            f"Loan request for A/C {account.account_no}",
            f"""Your Loan request for ${amount} has successfully sent to the admin. Wait for admin approval. After getting admin approval you will get the loan and also ge the confirmation mail""")

        return super().form_valid(form)


class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = "transactions/transaction_report.html"
    title = "Transactions"
    balance = 0
    model = TransactionModel

    def get_queryset(self):
        queryset = super().get_queryset().filter(account=self.request.user.account)

        start_date_str = self.request.GET.get('start_date')
        end_date_str = self.request.GET.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()

            queryset = queryset.filter(
                timestamp__date__gte=start_date, timestamp__date__lte=end_date)

            self.balance = TransactionModel.objects.filter(
                timestamp__date__gte=start_date, timestamp__date__lte=end_date
            ).aggregate(Sum('amount'))['amount__sum']
        else:
            self.balance = self.request.user.account.balance

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account
        })

        return context


class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(TransactionModel, id=loan_id)

        if loan.loan_approve:
            user_account = loan.account

            if loan.amount <= user_account.balance:
                user_account.balance -= loan.amount
                loan.balance_after_transaction = user_account.balance
                user_account.save()
                loan.transaction_type = LOAN_PAID
                loan.save()
                messages.success(
                    self.request, "Loan paid successfully")
                return redirect("transaction_report")
            else:
                messages.error(
                    self.request, "Loan amount is greater than available balance")
                return redirect("transaction_report")


class LoanListView(LoginRequiredMixin, ListView):
    model = TransactionModel
    template_name = "transactions/loan_request.html"
    context_object_name = "loans"

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = TransactionModel.objects.filter(
            account=user_account, transaction_type=LOAN)
        return queryset


class MoneyTransferView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, "transactions/money_transfer.html", {"form": MoneyTransferForm, "title" : "Money Transfer"})

    def post(self,request):
        form = MoneyTransferForm(request.POST)
        
        if form.is_valid():
            amount = form.cleaned_data.get("amount")
            account_no = form.cleaned_data.get("account_no")
            
            isBankAccountExists = UserBankAccountModel.objects.filter(account_no=account_no).count()
            if isBankAccountExists :
                to_account = UserBankAccountModel.objects.get(account_no=account_no)
                request.user.account.balance -= amount
                to_account.balance += amount
               
                request.user.account.save()
                to_account.save()

                TransactionModel.objects.create(
                    account = request.user.account,
                    amount = amount,
                    balance_after_transaction = request.user.account.balance,
                    transaction_type = TRANSFERRED,
                )
                TransactionModel.objects.create(
                    account = to_account,
                    amount = amount,
                    balance_after_transaction = to_account.balance,
                    transaction_type = RECEIVED,
                )
                send_transaction_emails(
                request.user,
                request.user.email,
                f"Successfully money Transferred to A/C {to_account.account_no}",
                f"""Your ${amount} of money transfer request has been done and your current balance is {request.user.account.balance}""")

                send_transaction_emails(
                to_account.account,
                to_account.account.email,
                f"Money received from A/C {request.user.account.account_no}",
                f"""Money ${amount} has been received from {request.user.account.account_no} and your current balance is {to_account.balance}""")

                messages.success(request, "Money has been transferred successfully")
                return redirect("transaction_report")
            else :
                messages.error(request, "Sorry no Bank account was found on this number!!")

        return render(request, "transactions/money_transfer.html", {"form": MoneyTransferForm, "title" : "Money Transfer"})

transactions/templates/transactions/loan_request.html
{% extends 'base.html' %} 

{% block head_title %}
    <title>{{ title }}</title>
{% endblock head_title %} 

{% block body %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md h-screen">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
  <hr />
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">LOAN ID</th>
        <th class="px-4 py-2">Loan Amount</th>
        <th class="px-4 py-2">Loan Approved</th>
        <th class="px-4 py-2">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for loan in loans %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
         {{ loan.id }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100"
          >
            {{ loan.amount }}
          </span>
        </td>
        <td class="px-4 py-2">
          {{ loan.loan_approve }}
        </td>
        <td class="px-4 py-2">
          {% if loan.loan_approve %}
          <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "pay" loan.id %}'>Pay</a>
          {% else %}
          <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock body %}

transactions/templates/transactions/money_transfer.html
{% extends 'base.html' %} 

{% block head_title %}
    <title>{{ title }}</title>
{% endblock head_title %}


 {% block body %}

<section class="h-screen">
    <div class="w-full flex mt-5 justify-center ">
        <div class="bg-white w-5/12 rounded-lg">
            {% if title == 'Request For Loan' %}
    <div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{%url 'loan_list'%}">View All Loan List</a></div>
            {% endif %}
            
            <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
            <form method="post" class="px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
               

                {% for field in form.visible_fields %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    <input class="shadow appearance-none border border-gray-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}">
                </div>
                {% if field.errors %} {% for error in field.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} {% endif %} {% endfor %}
                <div class="flex w-full justify-center">
                    <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                    Submit
                </button>
                </div>
            </form>
        </div>
        
    </div>
</section>
{% endblock body %}

transactions/templates/transactions/transaction_form.html
{% extends 'base.html' %} 

{% block head_title %}
    <title>{{ title }}</title>
{% endblock head_title %}


 {% block body %}

<section class="h-screen">
    <div class="w-full flex mt-5 justify-center ">
        <div class="bg-white w-5/12 rounded-lg">
            {% if title == 'Request For Loan' %}
    <div><a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{%url 'loan_list'%}">View All Loan List</a></div>
            {% endif %}
            
            <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
            <form method="post" class="px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
               

                {% for field in form.visible_fields %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    <input class="shadow appearance-none border border-gray-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}">
                </div>
                {% if field.errors %} {% for error in field.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} {% endif %} {% endfor %}
                <div class="flex w-full justify-center">
                    <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                    Submit
                </button>
                </div>
            </form>
        </div>
        
    </div>
</section>
{% endblock body %}

transactions/templates/transactions/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block head_title %} 
    <title>Transaction Reports</title>
{% endblock %} 

{% block body %}


<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md h-full">
  <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
  <hr />
  <form method="get" action="{% url 'transaction_report' %}">
    <div class="flex justify-center">
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2"
      >
        <label for="start_date">From:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="start_date"
          name="start_date"
        />
      </div>
 
      <div
        class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12"
      >
        <label for="end_date">To:</label>
        <input
          class="appearance-none w-full outline-none focus:outline-none active:outline-none"
          type="date"
          id="end_date"
          name="end_date"
        />
      </div>
      <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
        <button
          class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
          type="submit"
        >
          Filter
        </button>
      </div>
    </div>
  </form>
  <table
    class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500"
  >
    <thead class="bg-purple-900 text-white text-left">
      <tr
        class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold"
      >
        <th class="px-4 py-2">Date</th>
        <th class="px-4 py-2">Transaction Type</th>
        <th class="px-4 py-2">Amount</th>
        <th class="px-4 py-2">Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
          {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
          <span
            class="px-2 py-1 font-bold leading-tight rounded-sm {% if transaction.get_transaction_type_display == 'Withdrawal' %} text-red-700 bg-red-100 {% else %} text-green-700 bg-green-100 {% endif %}"
          >
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
          $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
      </tr>
      {% endfor %}
      <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
          $ {{ request.user.account.balance|floatformat:2|intcomma }}
        </th>
      </tr>
    </tbody>
  </table>
</div>
{% endblock body %}